#!/bin/bash

# Function to post status
post_status() {
    if [ $1 -eq 0 ]; then
        echo "Success: $2"
    else
        echo "Failure: $2"
    fi
}

# Delete /etc/hostname and /etc/hosts to allow recreation
rm -f /etc/hostname
post_status $? "Deleting /etc/hostname"
rm -f /etc/hosts
post_status $? "Deleting /etc/hosts"

# Delete SSH host keys
rm -v /etc/ssh/ssh_host_*

# Reconfigure openssh-server
dpkg-reconfigure openssh-server
post_status $? "openssh-server configuration"

# Update package list
apt update
post_status $? "Package list update"

# Upgrade packages
apt upgrade -y
post_status $? "Package upgrade"

# Install required packages
apt install -y nano git qemu-guest-agent wget curl samba nfs-kernel-server cifs-utils ca-certificates gnupg open-iscsi jq chrony
post_status $? "Package installation"

# Pause to allow NetworkManager to apply its configuration
sleep 5

# Remove domain and search sections from /etc/resolv.conf
sed -i '/^domain/d' /etc/resolv.conf
sed -i '/^search/d' /etc/resolv.conf

# Set /etc/resolv.conf to have multiple nameservers
echo -e "nameserver 192.200.0.1\nnameserver 172.200.0.1" >> /etc/resolv.conf
post_status $? "Updating /etc/resolv.conf"

# Backup the original chrony.conf file
cp /etc/chrony/chrony.conf /etc/chrony/chrony.conf.backup

# Comment out the line with the pool directive
sed -i 's/^pool 2.debian.pool.ntp.org iburst/#pool 2.debian.pool.ntp.org iburst/' /etc/chrony/chrony.conf

# Configure Chrony to use only one NTP server
echo "server 192.200.0.1 iburst" >> /etc/chrony/chrony.conf

# Enable and start Chrony service (use the appropriate service name for your system)
systemctl enable chrony
systemctl start chrony
post_status $? "Chrony service"

# Set timezone to Europe/Berlin within chrony.conf
echo "rtctimerange 0 1 Europe/Berlin" >> /etc/chrony/chrony.conf
post_status $? "Timezone configuration"

# Uninstall and clean up systemd-timesyncd
apt-get purge systemd-timesyncd -y
post_status $? "Uninstall systemd-timesyncd"

# Another pause to see if results ok
sleep 10

# Delete the incorrect default route
ip route del default via 172.200.0.1 dev ens19

# Add the correct default route for ens18
ip route add default via 192.200.1.1 dev ens18

# Update the routing table
ip route flush cache

# Reboot the server
echo "Rebooting the system..."
reboot
