#!/bin/bash

# Function to post status
post_status() {
    if [ $1 -eq 0 ]; then
        echo "Success: $2"
    else
        echo "Failure: $2"
    fi
}

# Delete /etc/hostname and /etc/hosts to allow recreation
rm -f /etc/hostname
post_status $? "Deleting /etc/hostname"
rm -f /etc/hosts
post_status $? "Deleting /etc/hosts"

# Delete SSH host keys
rm -v /etc/ssh/ssh_host_*

# Reconfigure openssh-server
dpkg-reconfigure openssh-server
post_status $? "openssh-server configuration"

sleep 5

# Update package list
apt update
post_status $? "Package list update"

# Upgrade packages
apt upgrade -y
post_status $? "Package upgrade"

# Install required packages
apt install -y nano git qemu-guest-agent wget curl samba nfs-kernel-server cifs-utils ca-certificates gnupg open-iscsi jq chrony
post_status $? "Package installation"

# Pause to allow NetworkManager to apply its configuration
sleep 15

# Set /etc/resolv.conf to have multiple nameservers
echo -e "nameserver 192.200.0.1\nnameserver 172.200.0.1" >> /etc/resolv.conf
post_status $? "Updating /etc/resolv.conf"

# Backup the original chrony.conf file
cp /etc/chrony/chrony.conf /etc/chrony/chrony.conf.backup

# Replace the line with the pool directive with the server directive
sed -i 's/^pool 2.debian.pool.ntp.org iburst/server 192.200.0.1 iburst/' /etc/chrony/chrony.conf
post_status $? "Updating chrony.conf"

# Enable and start Chrony service (use the appropriate service name for your system)
systemctl enable chrony
systemctl start chrony
post_status $? "Chrony service"

# Set timezone using timedatectl
timedatectl set-timezone Europe/Berlin
post_status $? "Timezone configuration"

# Uninstall and clean up systemd-timesyncd
apt-get purge systemd-timesyncd -y
post_status $? "Uninstall systemd-timesyncd"

# Another pause to see if results ok
sleep 10

# Modify /etc/network/interfaces for static IP on ens19
echo "
# Configured by script
auto ens19
iface ens19 inet static
    address 172.200.0.10
    netmask 255.255.0.0
    gateway 172.200.0.1
" >> /etc/network/interfaces

# Reboot the server
echo "Rebooting the system..."
reboot
